### PR TITLE
Load 15 posts per page, instead of 12

### PR DESCRIPTION
**Pull request by Digitalfear117**
I don't know if this is actually what I am supposed to do

### CODE REVIEW

**Comment by Lekuruu** [comment]
Is it that bad

**Comment by Digitalfear117** [comment]
imo it's quite annoying, 12 is too few

**Review by Lekuruu — COMMENTED** [review]
I am not too sure if it will break other stuff, so I'll have to test it later

**Comment by Digitalfear117** [comment]
okay

**Review by Lekuruu — APPROVED** [review]
Should work now.

**Pull request merged**
