### PR TITLE
Add `client` column to BenchmarkModel

### PR DESCRIPTION
**Pull request by Digitalfear117**
yessir

### CODE REVIEW

**Comment by Zordon1337** [comment]
i don't think so :trollface:

**Comment by iSlodinxOsu** [comment]
i promise you it's gonna happen, let em cook

**Comment by Lekuruu** [comment]
huh

**Comment by Lekuruu** [comment]
Okay, I just didn't see the other PRs.
Will review it soon.

**Review by Lekuruu — APPROVED** [review]

**Pull request merged**
