### PR TITLE
Use known bugs on downloads page

### PR DESCRIPTION
**Pull request by Zordon1337**
this pull request resolves https://github.com/osuTitanic/stern/issues/166

Added known bugs to download page

now imagine that we have to fill known bugs for at least 30% of clients in manifest :clueless:

### CODE REVIEW

**Comment by Lekuruu** [comment]
CSS is driving me crazy while reviewing this...

**Comment by Lekuruu** [comment]
Here is the current problem I have with this:

https://github.com/user-attachments/assets/e05f5c50-c312-438f-b67a-de59fc3bcaa8

I hope this is only Linux related. Can you check @Zordon1337 ?

**Comment by Zordon1337** [comment]
Is title param even set?

czw., 19 wrz 2024, 20:10 użytkownik Levi ***@***.***> napisał:

**Comment by Zordon1337** [comment]
Is title param even set?

**Comment by Lekuruu** [comment]
Well, you can clearly see in the video, that there is in fact, a title present.

**Comment by Zordon1337** [comment]
very weird, it was working fine for me on windows

**Comment by Zordon1337** [comment]
yep its still seems to work
image


im gonna try to apply your css changes and then check

**Comment by Zordon1337** [comment]
yep, thats seems to be the problem after applying your css title stopped working for me too

**Comment by Zordon1337** [comment]
> Oh yeah, no. I know why this is happening. I just wanted to know if its a linux-specific issue

nope, its windows also

**Comment by Lekuruu** [comment]
```
position: relative;
z-index: 1;
```
This makes no sense, but i'll take it.

**Comment by Zordon1337** [comment]
css our beloved

**Review by Lekuruu — APPROVED** [review]

**Pull request merged**
